[package]
name = "dockaya-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
dockaya-common = { path = "../dockaya-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "dockaya"
path = "src/main.rs"
